---
title: "Curriculum Vitae"
---

---
title: "Curriculum Vitae"
format:
  html:
    toc: false
---


::: {.grid}

::: {.g-col-4 .cv-sidebar}

## Contact

<i class="bi bi-envelope"></i> [carson_slater1@baylor.edu](mailto:carson_slater1@baylor.edu)  
<i class="bi bi-github"></i> [carsonslater](https://github.com/carsonslater)  
<i class="bi bi-linkedin"></i> [carsonslateratbaylor](https://www.linkedin.com/in/carsonslateratbaylor/)  
<i class="bi bi-instagram"></i> [carson.sl8r](https://www.instagram.com/carson.sl8r/)

## Education

**PhD, Statistical Science**  
Baylor University | *2024–2027 [Expected]*  
Research: Developing statistical methods for time series clustering with applications in urban water distribution processes.

**M.S., Statistical Science**  
Baylor University | *2023–2024*  
GPA: 3.86/4.0

**B.S., Applied Mathematics with Statistics**  
**B.A., Economics**  
Wheaton College (IL) | *2019–2023*  
GPA: 3.46/4.0, *Edman Presidential Scholarship*  
*Varsity Baseball Athlete (NCAA-DIII)*


## Skills

**Technology**  
Docker, Positron ($\approx$ VS Code), Git/Github, reveal.js, R/RStudio, SQL, duckDB, \LaTeX

**Python**  
pandas, numpy, PyTorch (Lightning), plotnine, seaborn, plotly, scikit-learn, Jupyter

**R**  
tidyverse (dplyr, ggplot2, etc.), TensorFlow (Keras), torch, shiny, RMarkdown/Quarto, rstan, rjags, caret, tidymodels, targets (gittargets, proffer, etc.)

**Stats & ML**  
statistical modeling, hypothesis testing, mixture models, time series, regression, linear mixed models, clustering, classification, deep learning, PCA, random forests, ensemble models (e.g., XGBoost), SVM, Bayesian methods, spatiotemporal modeling

**Coursework**  
Statistical Bioinformatics, Deep Learning, Bayesian Methods, Bayesian Theory, Survival Analysis, Time Series, Theory of Statistics, Statistical Methods, Computational Statistics, Numerical Analysis, Linear Algebra for Data Analysis, Mathematical Statistics, Machine Learning, Probability Theory, Real Analysis, Intensive Introduction to Computer Science (Harvard), Econometrics, Economics of Labor and Poverty


## Misc.

**Christian Character Award**  
Valley Christian HS  
*2019*

:::

::: {.g-col-8 .cv-main}

## Summary

Motivated graduate student seeking consulting opportunities. Aspiring applied statistician who loves to use statistical methods to empower people with insights for good stewardship.

## Experience

### Research Assistant
**Baylor University** | Waco, TX | *Jan 2024–Present*

*   Developing statistical methods for urban water distribution processes, leveraging unsupervised learning on time series for customer-level water utility data ($\sim$200k homes in Denver, CO).
*   Collaborated with domain experts in urban water demand planning to comprehend data and processes, perform robust analyses, and effectively communicate results.
*   Developed R Shiny dashboard to enable collaborators at Denver Water to visualize the outdoor irrigation trends for customers with advanced metering infrastructure.
*   Edited and reviewed material for an undergraduate intro to data science course. ([DOI: 10.7910/DVN/BZJW2E](https://doi.org/10.7910/DVN/BZJW2E))

### Graduate Assistant
**Baylor University** | Waco, TX | *Aug 2023–Dec 2025*

*   Consulted for ongoing interdisciplinary research in the computer engineering and environmental science departments, and for the American Holistic Nursing Association. Published academic projects in peer-reviewed journals.
*   Delivered quality reports for each client and had regular meetings to discuss the project, the methodology and results.
*   Teaching assistant for Computational Statistics (R).

### Academic Coach
**Wheaton Academy Center for Lifelong Learning** | West Chicago, IL | *Jan 2023–May 2023*

*   Mentored students 1-on-1 to sharpen math skills from Algebra I to AP Statistics.

### Mathematics Teaching Assistant
**Wheaton College** | Wheaton, IL | *Aug 2022–May 2023*

*   Facilitated help sessions for undergraduate students in the topics of Machine Learning and Probability Theory.


## Papers

### Assessing the Effects of Surface-Stabilized Zero-Valent Iron Nanoparticles (March 2025)
**[Paper](https://doi.org/10.3390/jfb16030113)**

*   Used ordinal regression and generalized linear models to understand relationships between nanoparticle coatings and bacterial inhibition.

### Assessing Interference with Regression Analysis Techniques (April 2024)
**[Paper](https://doi.org/10.1109/WMCS62019.2024.10619025)**

*   Used generalized additive models to predict pairwise interference in a Dynamic Spectrum Access context.
*   Presented at the 2024 IEEE Texas Symposium on Wireless and Microwave Circuits and Systems (WMCS).

## Volunteer

### Intern — Křesťanská Akademie Mladých
*Jun 2023–Aug 2023*

*   Built a blog to keep supporters updated on mission work.
*   Taught English and sports in schools and at camps; supported local CB churches.
*   Trained incoming short-term mission teams.

:::

:::
